"""initial_schema_13_tables

Revision ID: 08b6189ffc35
Revises: 
Create Date: 2026-03-07 00:04:17.448987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08b6189ffc35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pgcrypto for gen_random_uuid()
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='student', nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('student', 'admin')", name='chk_users_role'),
    sa.CheckConstraint('disabled_at IS NULL OR disabled_reason IS NOT NULL', name='chk_users_disabled_reason'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action_time', 'audit_logs', ['action', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_audit_logs_admin_time', 'audit_logs', ['admin_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('consent_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'archived')", name='chk_consent_versions_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('idx_consent_versions_active', 'consent_versions', ['status'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_prt_token_active', 'password_reset_tokens', ['token_hash'], unique=False, postgresql_where=sa.text('used_at IS NULL'))
    op.create_index('idx_prt_user_created', 'password_reset_tokens', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('save_history', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ui_language', sa.String(), server_default='es', nullable=False),
    sa.Column('tts_voice', sa.String(), nullable=True),
    sa.Column('accessibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checkin_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('preferred_chat_mode', sa.String(), server_default='chat', nullable=False),
    sa.CheckConstraint("preferred_chat_mode IN ('chat', 'avatar')", name='chk_preferences_chat_mode'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('topic_hint', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checkin_opt_in', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('checkin_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checkin_completed_at', sa.DateTime(), nullable=True),
    sa.Column('avatar_used', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_user_time', 'sessions', ['user_id', 'started_at'], unique=False)
    op.create_index('uq_sessions_user_active', 'sessions', ['user_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_table('survey_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('administered_at', sa.DateTime(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('imported_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("instrument IN ('sus', 'empathy_rubric', 'wellbeing_pre', 'wellbeing_post')", name='chk_survey_responses_instrument'),
    sa.CheckConstraint("phase IN ('pre', 'post')", name='chk_survey_responses_phase'),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'instrument', 'phase', name='uq_survey_user_instrument_phase')
    )
    op.create_index('idx_survey_instrument_phase', 'survey_responses', ['instrument', 'phase'], unique=False)
    op.create_index('idx_survey_user', 'survey_responses', ['user_id'], unique=False, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('system_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('consents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('consent_version_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("scope IN ('solo_uso', 'uso_mejora_anon')", name='chk_consents_scope'),
    sa.ForeignKeyConstraint(['consent_version_id'], ['consent_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'consent_version_id', name='uq_consents_user_version')
    )
    op.create_index('idx_consents_user_latest', 'consents', ['user_id', sa.literal_column('accepted_at DESC')], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_sha256', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_completion', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("role IN ('system', 'user', 'assistant')", name='chk_messages_role'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_session_time', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_messages_latency', 'messages', ['latency_ms'], unique=False, postgresql_where=sa.text("role = 'assistant' AND latency_ms IS NOT NULL"))
    op.create_table('safety_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'reviewed', 'resolved')", name='chk_safety_events_status'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_safety_events_status', 'safety_events', ['status'], unique=False)
    op.create_index('idx_safety_events_type', 'safety_events', ['event_type'], unique=False)
    op.create_index('idx_safety_events_user_time', 'safety_events', ['user_id', 'created_at'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("kind IN ('audio', 'image', 'doc')", name='chk_attachments_kind'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attachments_message', 'attachments', ['message_id'], unique=False)
    op.create_table('message_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("reason IN ('hallucination', 'harmful', 'privacy', 'low_empathy', 'other')", name='chk_message_reports_reason'),
    sa.CheckConstraint("status IN ('open', 'triaged', 'resolved', 'dismissed')", name='chk_message_reports_status'),
    sa.CheckConstraint('severity IS NULL OR (severity >= 1 AND severity <= 5)', name='chk_message_reports_severity'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_reports_msg_time', 'message_reports', ['message_id', 'created_at'], unique=False)
    op.create_index('idx_message_reports_reporter', 'message_reports', ['reporter_id'], unique=False)
    op.create_index('idx_message_reports_status', 'message_reports', ['status'], unique=False)
    op.create_index('uq_message_reports_msg_user', 'message_reports', ['message_id', 'reporter_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_message_reports_msg_user', table_name='message_reports')
    op.drop_index('idx_message_reports_status', table_name='message_reports')
    op.drop_index('idx_message_reports_reporter', table_name='message_reports')
    op.drop_index('idx_message_reports_msg_time', table_name='message_reports')
    op.drop_table('message_reports')
    op.drop_index('idx_attachments_message', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('idx_safety_events_user_time', table_name='safety_events')
    op.drop_index('idx_safety_events_type', table_name='safety_events')
    op.drop_index('idx_safety_events_status', table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_index('idx_messages_latency', table_name='messages', postgresql_where=sa.text("role = 'assistant' AND latency_ms IS NOT NULL"))
    op.drop_index('idx_messages_session_time', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_consents_user_latest', table_name='consents')
    op.drop_table('consents')
    op.drop_table('system_config')
    op.drop_index('idx_survey_user', table_name='survey_responses', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('idx_survey_instrument_phase', table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index('uq_sessions_user_active', table_name='sessions', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index('idx_sessions_user_time', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('preferences')
    op.drop_index('idx_prt_user_created', table_name='password_reset_tokens')
    op.drop_index('idx_prt_token_active', table_name='password_reset_tokens', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_table('password_reset_tokens')
    op.drop_index('idx_consent_versions_active', table_name='consent_versions', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('consent_versions')
    op.drop_index('idx_audit_logs_admin_time', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
